// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TMorph.Schema
{

public enum ComType : long
{
 Undef = 0,
 Token = 1,
 Synt = 2,
 Morph = 3,
 Separ = 4,
 Repar = 5,
 SaveLex = 11,
 GetWord = 12,
 SavePara = 13,
 ReadPara = 14,
};


}
