// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TMorph.Schema
{

using global::System;
using global::FlatBuffers;

public struct Container : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Container GetRootAsContainer(ByteBuffer _bb) { return GetRootAsContainer(_bb, new Container()); }
  public static Container GetRootAsContainer(ByteBuffer _bb, Container obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Container __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long CtId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string CreatedAt { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetCreatedAtBytes() { return __p.__vector_as_arraysegment(6); }
  public string Name { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(8); }
  public long ParentId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Container> CreateContainer(FlatBufferBuilder builder,
      long ct_id = 0,
      StringOffset created_atOffset = default(StringOffset),
      StringOffset nameOffset = default(StringOffset),
      long parent_id = 0) {
    builder.StartObject(4);
    Container.AddParentId(builder, parent_id);
    Container.AddCtId(builder, ct_id);
    Container.AddName(builder, nameOffset);
    Container.AddCreatedAt(builder, created_atOffset);
    return Container.EndContainer(builder);
  }

  public static void StartContainer(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddCtId(FlatBufferBuilder builder, long ctId) { builder.AddLong(0, ctId, 0); }
  public static void AddCreatedAt(FlatBufferBuilder builder, StringOffset createdAtOffset) { builder.AddOffset(1, createdAtOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(2, nameOffset.Value, 0); }
  public static void AddParentId(FlatBufferBuilder builder, long parentId) { builder.AddLong(3, parentId, 0); }
  public static Offset<Container> EndContainer(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Container>(o);
  }
};


}
