// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TMorph.Schema
{

using global::System;
using global::FlatBuffers;

public struct Document : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Document GetRootAsDocument(ByteBuffer _bb) { return GetRootAsDocument(_bb, new Document()); }
  public static Document GetRootAsDocument(ByteBuffer _bb, Document obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Document __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long DocId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string CtId { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetCtIdBytes() { return __p.__vector_as_arraysegment(6); }
  public string CreatedAt { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetCreatedAtBytes() { return __p.__vector_as_arraysegment(8); }
  public string Name { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(10); }

  public static Offset<Document> CreateDocument(FlatBufferBuilder builder,
      long doc_id = 0,
      StringOffset ct_idOffset = default(StringOffset),
      StringOffset created_atOffset = default(StringOffset),
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartObject(4);
    Document.AddDocId(builder, doc_id);
    Document.AddName(builder, nameOffset);
    Document.AddCreatedAt(builder, created_atOffset);
    Document.AddCtId(builder, ct_idOffset);
    return Document.EndDocument(builder);
  }

  public static void StartDocument(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddDocId(FlatBufferBuilder builder, long docId) { builder.AddLong(0, docId, 0); }
  public static void AddCtId(FlatBufferBuilder builder, StringOffset ctIdOffset) { builder.AddOffset(1, ctIdOffset.Value, 0); }
  public static void AddCreatedAt(FlatBufferBuilder builder, StringOffset createdAtOffset) { builder.AddOffset(2, createdAtOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(3, nameOffset.Value, 0); }
  public static Offset<Document> EndDocument(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Document>(o);
  }
};


}
