// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TMorph.Schema
{

using global::System;
using global::FlatBuffers;

public struct Paragraph : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Paragraph GetRootAsParagraph(ByteBuffer _bb) { return GetRootAsParagraph(_bb, new Paragraph()); }
  public static Paragraph GetRootAsParagraph(ByteBuffer _bb, Paragraph obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Paragraph __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long PgId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long CreatedAt { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Paragraph> CreateParagraph(FlatBufferBuilder builder,
      long pg_id = 0,
      long created_at = 0) {
    builder.StartObject(2);
    Paragraph.AddCreatedAt(builder, created_at);
    Paragraph.AddPgId(builder, pg_id);
    return Paragraph.EndParagraph(builder);
  }

  public static void StartParagraph(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddPgId(FlatBufferBuilder builder, long pgId) { builder.AddLong(0, pgId, 0); }
  public static void AddCreatedAt(FlatBufferBuilder builder, long createdAt) { builder.AddLong(1, createdAt, 0); }
  public static Offset<Paragraph> EndParagraph(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Paragraph>(o);
  }
};


}
