// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TMorph.Schema
{

using global::System;
using global::FlatBuffers;

public struct Paragraph : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Paragraph GetRootAsParagraph(ByteBuffer _bb) { return GetRootAsParagraph(_bb, new Paragraph()); }
  public static Paragraph GetRootAsParagraph(ByteBuffer _bb, Paragraph obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Paragraph __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long PgId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long DocId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string CreatedAt { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetCreatedAtBytes() { return __p.__vector_as_arraysegment(8); }

  public static Offset<Paragraph> CreateParagraph(FlatBufferBuilder builder,
      long pg_id = 0,
      long doc_id = 0,
      StringOffset created_atOffset = default(StringOffset)) {
    builder.StartObject(3);
    Paragraph.AddDocId(builder, doc_id);
    Paragraph.AddPgId(builder, pg_id);
    Paragraph.AddCreatedAt(builder, created_atOffset);
    return Paragraph.EndParagraph(builder);
  }

  public static void StartParagraph(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddPgId(FlatBufferBuilder builder, long pgId) { builder.AddLong(0, pgId, 0); }
  public static void AddDocId(FlatBufferBuilder builder, long docId) { builder.AddLong(1, docId, 0); }
  public static void AddCreatedAt(FlatBufferBuilder builder, StringOffset createdAtOffset) { builder.AddOffset(2, createdAtOffset.Value, 0); }
  public static Offset<Paragraph> EndParagraph(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Paragraph>(o);
  }
};


}
