// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TMorph.Schema
{

public enum ServType : sbyte
{
 svMorph = 0,
 svSUBD = 1,
};


}
