//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MorphMQserver.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class MorphMQsrvr : global::System.Configuration.ApplicationSettingsBase {
        
        private static MorphMQsrvr defaultInstance = ((MorphMQsrvr)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MorphMQsrvr())));
        
        public static MorphMQsrvr Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Work\\Framework\\GrammarEngine\\src\\bin-windows64\\dictionary.xml")]
        public string DictPath {
            get {
                return ((string)(this["DictPath"]));
            }
        }
    }
}
