// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TMorph.Schema
{

public enum MessType : sbyte
{
 mRequest = 0,
 mReplay = 1,
};


}
