// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TMorph.Schema
{

using global::System;
using global::FlatBuffers;

public struct Param : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Param GetRootAsParam(ByteBuffer _bb) { return GetRootAsParam(_bb, new Param()); }
  public static Param GetRootAsParam(ByteBuffer _bb, Param obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Param __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
  public string Value { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetValueBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<Param> CreateParam(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      StringOffset valueOffset = default(StringOffset)) {
    builder.StartObject(2);
    Param.AddValue(builder, valueOffset);
    Param.AddName(builder, nameOffset);
    return Param.EndParam(builder);
  }

  public static void StartParam(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, StringOffset valueOffset) { builder.AddOffset(1, valueOffset.Value, 0); }
  public static Offset<Param> EndParam(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Param>(o);
  }
};


}
